### ISSUE TITLE
Error with loopbe1

### ISSUE THREAD

**Issue by GoulagmanYt** [Mathieu52/OSCMidi#1]
"An issue has occurred while trying to connect to device:
LoopBe Internal MIDI 2"

**Comment by GoulagmanYt** [comment]
i can't set Loopbe to output ( i don't have this message if i set LoopBe to input)

**Comment by GoulagmanYt** [comment]
![image_2024-07-06_164555247](https://github.com/Mathieu52/OSCMidi/assets/121605137/164229fc-2128-4c44-924d-e98a8725794c)

**Comment by Mathieu52** [comment]
It means it's unable to open the port, most likely because it's already open by another program. If it's something else, I'll have to investigate the MIDI library I'm using and it may take a while to fix. Can you close everything except loopbe1 and the OSCMidi and see if that changes anything, try restarting OSCMidi that might also help

**Comment by GoulagmanYt** [comment]
Im using rtp midi for input and its on port 128 so idk

**Comment by Mathieu52** [comment]
If the input is working it shouldn't have any effect on the output

**Comment by GoulagmanYt** [comment]
look

https://github.com/Mathieu52/OSCMidi/assets/121605137/f18d576e-0cbc-41c1-86dc-1d33db7d2320

**Comment by GoulagmanYt** [comment]
screen recorder don't show error window wtf

**Comment by GoulagmanYt** [comment]
But its working when its in input and not if its output 
![image_2024-07-06_171521907](https://github.com/Mathieu52/OSCMidi/assets/121605137/0cfc4b79-5df0-4ec2-a93d-4f5000220e10)

**Comment by Mathieu52** [comment]
I'll compile a new version that will tell me what the error is and send it to you through email.

**Comment by Mathieu52** [comment]
I may have found the issue in the code, I'll push a new version of the program.

**Comment by GoulagmanYt** [comment]
ok tyvm ur so fast bro

**Comment by Mathieu52** [comment]
Try this version, you'll have to replace the OSCMidi file manually in "Program Files (x86)" as I don't have the program to make the installer on hand: https://github.com/Mathieu52/OSCMidi/releases/tag/1.0.6

**Comment by GoulagmanYt** [comment]
Ok im doing it ...

**Comment by GoulagmanYt** [comment]
I have an error 
![image_2024-07-06_180647233](https://github.com/Mathieu52/OSCMidi/assets/121605137/e07231bf-8bcc-4c61-84f1-b57ea6865aeb)

**Comment by GoulagmanYt** [comment]
when i lunch app

**Comment by Mathieu52** [comment]
I had that issue when I didn't decompress the .zip file

**Comment by GoulagmanYt** [comment]
I used winRAR to decompress ....

**Comment by GoulagmanYt** [comment]
its because of .exe

**Comment by GoulagmanYt** [comment]
when i ctrl+c ctrl+v .exe it broke

**Comment by Mathieu52** [comment]
Did you just copy the .exe or the entire folder?

**Comment by GoulagmanYt** [comment]
entire folder

**Comment by GoulagmanYt** [comment]
when i only copy folder and not the .exe i have this error 
![image_2024-07-06_181329873](https://github.com/Mathieu52/OSCMidi/assets/121605137/a05d9575-058a-4b38-be52-502b680ca1e3)

**Comment by GoulagmanYt** [comment]
![image_2024-07-06_181437007](https://github.com/Mathieu52/OSCMidi/assets/121605137/9036e7bf-8d83-4f1c-a2f1-3a4b1ebf519b)

**Comment by Mathieu52** [comment]
I've updated the zip file in release 1.0.6. I'm not sure it will fix the problem though

**Comment by Mathieu52** [comment]
If this doesn't work, I'll try compiling it on a different computer

**Comment by GoulagmanYt** [comment]
I have the same error when i copy .exe

**Comment by GoulagmanYt** [comment]
If i only copy files, app don't launch

**Comment by Mathieu52** [comment]
I could give you the instructions to compile it on your own computer, it's not that complex

**Comment by GoulagmanYt** [comment]
ok

**Comment by GoulagmanYt** [comment]
should i download smth ?

**Comment by Mathieu52** [comment]
- First you need to download python from the Microsoft Store : https://www.microsoft.com/store/productId/9NCVDN91XZQP?ocid=pdpshare

**Comment by GoulagmanYt** [comment]
done

**Comment by Mathieu52** [comment]
- Then download the source code zip in the 1.0.6 release

**Comment by GoulagmanYt** [comment]
done too :)

**Comment by Mathieu52** [comment]
- Decompress the zip and click on it, there might be open in terminal option (I'm using Window 11 so it might be different for you)

![Capture d’écran, le 2024-07-06 à 12 57 42](https://github.com/Mathieu52/OSCMidi/assets/47650386/0ba7c230-9ec8-460a-8e7b-08c08c7f8128)

**Comment by GoulagmanYt** [comment]
i have win 11 too np

**Comment by Mathieu52** [comment]
- Type the following lines one by one in the terminal
- cd src
- pip install -r requirements.txt
- pip install -U pyinstaller
- python -m PyInstaller main.spec

**Comment by Mathieu52** [comment]
Take screenshot at each step if possible, so that if there is any issue we'll be able to diagnose it

**Comment by GoulagmanYt** [comment]
![Capture d’écran 2024-07-06 191215](https://github.com/Mathieu52/OSCMidi/assets/121605137/9ec91af2-70de-4472-9ea9-aae6ba3d563d)
![image_2024-07-06_191240801](https://github.com/Mathieu52/OSCMidi/assets/121605137/1facbe77-3fc9-4bf6-a6c9-e505f483bb15)

**Comment by Mathieu52** [comment]
That one worked fine

**Comment by GoulagmanYt** [comment]
![image_2024-07-06_191433570](https://github.com/Mathieu52/OSCMidi/assets/121605137/297d5c4c-0ec1-4763-8e4f-a81241bb4aad)

**Comment by Mathieu52** [comment]
That one is also fine

**Comment by GoulagmanYt** [comment]
![image_2024-07-06_191753079](https://github.com/Mathieu52/OSCMidi/assets/121605137/2a4e853a-c3fb-4175-952d-a59e8c557e04)

**Comment by GoulagmanYt** [comment]
no errors before, its all white lines

**Comment by GoulagmanYt** [comment]
nvm its maybe errors 
![image_2024-07-06_191904378](https://github.com/Mathieu52/OSCMidi/assets/121605137/32b4d4a0-2714-4bbc-8f47-8bffcd6fa286)

**Comment by Mathieu52** [comment]
- Can you type, to get the python version
- python -V

**Comment by GoulagmanYt** [comment]
![image_2024-07-06_192252595](https://github.com/Mathieu52/OSCMidi/assets/121605137/3ce4a5aa-3f64-4caa-9938-a02c7070b89f)

**Comment by GoulagmanYt** [comment]
ye wrong version

**Comment by GoulagmanYt** [comment]
im updating it

**Comment by Mathieu52** [comment]
Don't update it too far or it might not work either, in worse case we'll just have to redo all the command but with pip -> pip3.12 and python -> python3.12

**Comment by GoulagmanYt** [comment]
ok

**Comment by GoulagmanYt** [comment]
how can i install a specific version of pip ?

**Comment by Mathieu52** [comment]
It should update itself along with python and should have install the right version from the Microsoft Store

**Comment by GoulagmanYt** [comment]
i restart the same procedure and i have no errors or warnings

**Comment by GoulagmanYt** [comment]
so i type Y ?

**Comment by Mathieu52** [comment]
Yes

**Comment by GoulagmanYt** [comment]
ok

**Comment by GoulagmanYt** [comment]
and now ?

**Comment by Mathieu52** [comment]
Can you send a screenshot, it should tell you where it built it

**Comment by GoulagmanYt** [comment]
too late i found it :)

**Comment by GoulagmanYt** [comment]
![image_2024-07-06_193412005](https://github.com/Mathieu52/OSCMidi/assets/121605137/db2be5c0-541e-44aa-ba35-06fb6e4adbf7)

**Comment by Mathieu52** [comment]
Does it launch correctly?

**Comment by GoulagmanYt** [comment]
Lets gooo its working no errors

**Comment by GoulagmanYt** [comment]
Tyvm

**Comment by GoulagmanYt** [comment]
I gonna test on vrchat

**Comment by Mathieu52** [comment]
You're welcome, does the output also work?

**Comment by GoulagmanYt** [comment]
Yes

**Comment by Mathieu52** [comment]
I can get on vrchat if doesn't work correctly there

**Comment by GoulagmanYt** [comment]
ok i gonna test tomorrow

**Comment by GoulagmanYt** [comment]
when i hit start and set loopbe to input in my DAW its not working...

**Comment by GoulagmanYt** [comment]
like i dont have piano sound in my DAW

**Comment by GoulagmanYt** [comment]
and when i change imput to my piano its working so its because of the app

**Comment by Mathieu52** [comment]
Sorry for the delay, I'm working on it now

**Comment by Mathieu52** [comment]
I'll push a new version in a few minutes, I tested it properly this time, and it's working

**Comment by Mathieu52** [comment]
We'll have to do the same thing as yesterday to make sure it works on your computer

**Comment by Mathieu52** [comment]
https://github.com/Mathieu52/OSCMidi/releases/tag/1.0.7

**Comment by Mathieu52** [comment]
> and when i change imput to my piano its working so its because of the app

It was because of a typo wrote sendMessage instead of send_message, it basically wasn't sending what it got from the input to the output

**Comment by GoulagmanYt** [comment]
ok ty will test it

**Comment by GoulagmanYt** [comment]
its working but on vr chat whe a key is pressed, she stay down and don't go up

**Comment by Mathieu52** [comment]
Which avatar are you using, I remember that one of them has some kind of issue

**Comment by GoulagmanYt** [comment]
i have same error with all 3 avatars

**Comment by GoulagmanYt** [comment]
im usig this one rn 
![Capture d’écran 2024-07-07 164303](https://github.com/Mathieu52/OSCMidi/assets/121605137/0ce85ac0-34dc-4bbd-8bdb-4e46c9625143)
![Capture d’écran 2024-07-07 164247](https://github.com/Mathieu52/OSCMidi/assets/121605137/fbd7059f-b6d1-46a5-860d-40cd0a1b2ff7)

**Comment by GoulagmanYt** [comment]
![Capture d’écran 2024-07-07 164342](https://github.com/Mathieu52/OSCMidi/assets/121605137/483f3d64-2d41-42a6-8ee5-790e3a438f7f)
![Capture d’écran 2024-07-07 164342](https://github.com/Mathieu52/OSCMidi/assets/121605137/bcae423c-c080-4f4c-91e3-efabc1b5ceee)

**Comment by Mathieu52** [comment]
Publishing a new version in a few minutes, I didn't account for the fact that some Piano don't exactly implement MIDI correctly

**Comment by Mathieu52** [comment]
https://github.com/Mathieu52/OSCMidi/releases/tag/1.0.8

**Comment by Mathieu52** [comment]
Have you had the time to test the fix?

**Comment by GoulagmanYt** [comment]
im unzipping the programm...

**Comment by GoulagmanYt** [comment]
when i start the programm and click start,midi input in my DAW isn't working

**Comment by Mathieu52** [comment]
There is no MIDI or your DAW gives you an error message

**Comment by GoulagmanYt** [comment]
nah my loopbe is broken idk why

**Comment by GoulagmanYt** [comment]
when i connect loopbe to rtpmidi output and connect to my daw its not working too ...

**Comment by GoulagmanYt** [comment]
im reinstalling it

**Comment by GoulagmanYt** [comment]
ok works now.. i gonna test on vr chat

**Comment by GoulagmanYt** [comment]
i have the same problem... keys are stuck

**Comment by GoulagmanYt** [comment]
my midis event looks like that 
![image_2024-07-07_191957601](https://github.com/Mathieu52/OSCMidi/assets/121605137/b8097800-336c-4475-b251-ec3b2ca2d3da)

**Comment by GoulagmanYt** [comment]
when notes are off its note on with 0 velocity idk why

**Comment by Mathieu52** [comment]
The standard is to send note_off and a velocity of 0, but some piano only send velocity = 0 with note_on

**Comment by Mathieu52** [comment]
I hadn't taken into account that, but it should have been taken into account in the version we just tested, it's probably and error on my end

**Comment by Mathieu52** [comment]
I'll publish a new version again, and we'll run it in debug, we won't have to compile it
- cd src
- python3.12 main.py

**Comment by Mathieu52** [comment]
https://github.com/Mathieu52/OSCMidi/releases/tag/1.0.9

**Comment by GoulagmanYt** [comment]
![image_2024-07-07_194114357](https://github.com/Mathieu52/OSCMidi/assets/121605137/19b05a7f-bdb3-4f4f-813d-70a56d145464)
ok im testing it

**Comment by Mathieu52** [comment]
Now when you start it and press on key, we should see what it sees

**Comment by GoulagmanYt** [comment]
yes 
![Uploading image_2024-07-07_194446210.png…]()

**Comment by GoulagmanYt** [comment]
![image_2024-07-07_194608204](https://github.com/Mathieu52/OSCMidi/assets/121605137/f240f1a2-184e-4067-aae0-5c1b14e4635a)

**Comment by Mathieu52** [comment]
I think I found the issue, I'll publish a new version

**Comment by GoulagmanYt** [comment]
wtf when app wasn't started it was working and when i hit start it brocke LoopBE

**Comment by Mathieu52** [comment]
https://github.com/Mathieu52/OSCMidi/releases/tag/1.0.10

**Comment by GoulagmanYt** [comment]
after a few times i see 
![Capture d’écran 2024-07-07 194705](https://github.com/Mathieu52/OSCMidi/assets/121605137/8173f40e-a57a-4e3b-970c-2b450d93f0a6)

**Comment by Mathieu52** [comment]
It just ran out of space for it's keys because it never unpress them

**Comment by GoulagmanYt** [comment]
ye and after loopbe mute himself

**Comment by GoulagmanYt** [comment]
i just saw it

**Comment by Mathieu52** [comment]
For the new version run in debug, it's faster for testing

**Comment by GoulagmanYt** [comment]
its working but if keys are down for a long time and other keys are played, some keys gets stuck

**Comment by Mathieu52** [comment]
Can you send a picture of the terminal when that happens

**Comment by GoulagmanYt** [comment]
ok

**Comment by GoulagmanYt** [comment]
![image_2024-07-07_195655782](https://github.com/Mathieu52/OSCMidi/assets/121605137/b34ab7dc-49cf-49c7-b99e-07f047db73ea)

**Comment by GoulagmanYt** [comment]
![Capture d’écran 2024-07-07 200011](https://github.com/Mathieu52/OSCMidi/assets/121605137/9f3c677c-bbf4-4077-afb5-0b5b93f73e56)

**Comment by GoulagmanYt** [comment]
and when i close terminal, python stop but my daw continue to recieve midi from my piano . Like app is stop but piano to loop be continue to work

**Comment by Mathieu52** [comment]
It just mean it probably didn't close cleanly and the sending thread is still active

**Comment by Mathieu52** [comment]
The program is telling us that it's sending all the off-key correctly, so it might be a VRChat issue, also if you're using the latest version of the avatar it hasn't been completely tested

**Comment by Mathieu52** [comment]
It was given to me as untested

**Comment by Mathieu52** [comment]
It might behave better if you compile it, I'd get on vrchat to test it, but I can't right now

**Comment by GoulagmanYt** [comment]
For what version of avatar is it working ? And how can I download a lower version ?Le 7 juil. 2024 à 20:06, Xz3ra ***@***.***> a écrit :﻿
The program is telling us that it's sending all the off-key correctly, so it might be a VRChat issue, also if you're using the latest version of the avatar it hasn't been completely tested

**Comment by Mathieu52** [comment]
I have personally tested these two : 
- avtr_f5648902-719f-4193-80b9-8d1581f076b4 - Fresh Pianist, has lightup keys
- avtr_2ed21ba8-f484-4fd0-b251-0e53dfe3c9c9 - OSC Piano, has keydown keys and is properly synced with mic audio

**Comment by GoulagmanYt** [comment]
Ok i will try to compile itLe 7 juil. 2024 à 20:08, Xz3ra ***@***.***> a écrit :﻿
It might behave better if you compile it, I'd get on vrchat to test if but I can't right now

**Comment by GoulagmanYt** [comment]
I have both …Le 7 juil. 2024 à 20:11, Xz3ra ***@***.***> a écrit :﻿
I have personally tested these two :

avtr_f5648902-719f-4193-80b9-8d1581f076b4 - Fresh Pianist, has lightup keys
avtr_2ed21ba8-f484-4fd0-b251-0e53dfe3c9c9 - OSC Piano, has keydown keys and is properly synced with mic audio

**Comment by Mathieu52** [comment]
And they don't work either?

**Comment by GoulagmanYt** [comment]
I will compile it and test it a second time ….Le 7 juil. 2024 à 20:16, Xz3ra ***@***.***> a écrit :﻿
And they don't work either

**Comment by Mathieu52** [comment]
I just tested all 3 avatars on vrchat and I don't get have any key getting stuck no matter what I do

**Comment by GoulagmanYt** [comment]
Ok tyvm everything is working after compiling it and restarting my PC

**Comment by GoulagmanYt** [comment]
Tyvm for ur time

**Comment by Mathieu52** [comment]
Amazing! You're welcome, if you have issues again, feel free to reach out

**Comment by GoulagmanYt** [comment]
ok ty

**Comment by GoulagmanYt** [comment]
just a last question.. what is particle settings how it works and what it does ?

**Comment by Mathieu52** [comment]
It doesn't do anything on the current avatars, but it sends data that could be used to make particles, it allows you to specify the particle limit and how long the particles should live and contains info about which key created the particle. I implemented it because it was a feature of the project this project is inspired from: https://github.com/brianops1/OSCMidi

**Comment by Mathieu52** [comment]
https://github.com/brianops1/OSCMidi/issues/2
